
version: '3.7'
services:
  db:
    image: mysql:5.7
    volumes:
        - db_data1:/var/lib/mysql
    restart: always
    ports:
        - 3307:3306
    environment:
        MYSQL_ROOT_PASSWORD: admin123
        MYSQL_DATABASE: covid
        MYSQL_USER: admin
        MYSQL_PASSWORD: admin123
  jupyter:
    image: jupyter/base-notebook
    ports:
      - 8888:8888
    volumes:
      - db_data1:/
    depends_on: 
      - db
volumes:
  db_data1: